# $Copyright:	$
# Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
# Sequent Computer Systems, Inc.   All rights reserved.
#  
# This software is furnished under a license and may be used
# only in accordance with the terms of that license and with the
# inclusion of the above copyright notice.   This software may not
# be provided or otherwise made available to, or used by, any
# other person.  No title to or ownership of the software is
# hereby transferred.

# $Header: Makefile.proto 1.3 86/03/17 $
#

print: Contents
Contents: contents.t
	tpf -X -M"-ms ../liberal" $? >$@

print: Copyr
Copyr: copyr.t
	tpf -X -M $? >$@

print: Manuals
Manuals: manuals.t
	tpf -X -M $? >$@

# print: Revisions
# Revisions: revisions.t
# 	tpf -X $? >$@

print: Title
Title: title.t
	tpf -X -Mtmac.ti $? >$@
