.\" $Copyright:	$
.\" Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
.\" Sequent Computer Systems, Inc.   All rights reserved.
.\"  
.\" This software is furnished under a license and may be used
.\" only in accordance with the terms of that license and with the
.\" inclusion of the above copyright notice.   This software may not
.\" be provided or otherwise made available to, or used by, any
.\" other person.  No title to or ownership of the software is
.\" hereby transferred.
...
.V= $Header: wump.6 1.4 86/05/13 $
.TH WUMP 6 "\*(V)" "7th Edition"
.SH NAME
wump \- the game of hunt-the-wumpus
.SH SYNOPSIS
.B /usr/games/wump
.SH DESCRIPTION
.I Wump
plays the game of `Hunt the Wumpus.'
A Wumpus is a creature that lives in a cave with several rooms
connected by tunnels.
You wander among the rooms, trying to
shoot the Wumpus with an arrow, meanwhile avoiding
being eaten by the Wumpus and falling into Bottomless Pits.
There are also Super Bats which are likely to pick you up
and drop you in some random room.
.PP
The program asks various questions which you answer one per line;
it will give a more detailed description if you want.
.PP
This program is based on one described in
.I "People's Computer Company,"
.I 2,
2 (November 1973).
