.\" $Copyright:	$
.\" Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
.\" Sequent Computer Systems, Inc.   All rights reserved.
.\"  
.\" This software is furnished under a license and may be used
.\" only in accordance with the terms of that license and with the
.\" inclusion of the above copyright notice.   This software may not
.\" be provided or otherwise made available to, or used by, any
.\" other person.  No title to or ownership of the software is
.\" hereby transferred.
...
.V= $Header: ac.8 1.5 87/05/27 $
.TH AC 8 "\*(V)" "4BSD"
.SH NAME
ac \- login accounting
.SH SYNOPSIS
.B /usr/etc/ac
[
.B \-w
wtmp ] [
.B \-p
] [
.B \-d
] [ people ] ...
.SH DESCRIPTION
.I Ac
produces a printout giving
connect time
for each user who has logged in
during the life of the current
.I wtmp
file.
A total is also produced.
.B \-w
is used to specify an alternate
.IR wtmp ""
file.
.B \-p
prints individual totals; without this option,
only totals are printed.
.B \-d
causes a printout for each midnight to midnight
period.
Any
.I people
will limit the
printout to only the specified login names.
If no
.IR wtmp ""
file is given,
.I /usr/adm/wtmp
is used.
.PP
The accounting file
.I /usr/adm/wtmp
is maintained by
.I init
and
.I login.
Neither of these programs creates the file,
so if it does not exist
no connect-time accounting is done.
To start accounting, it should be created with length 0.
On the other hand if the file is left undisturbed it will
grow without bound, so periodically any information
desired should be collected and the file truncated.
.SH FILES
/usr/adm/wtmp
.SH "SEE ALSO"
init(8), sa(8), login(1), utmp(5).
