.\" $Copyright:	$
.\" Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
.\" Sequent Computer Systems, Inc.   All rights reserved.
.\"  
.\" This software is furnished under a license and may be used
.\" only in accordance with the terms of that license and with the
.\" inclusion of the above copyright notice.   This software may not
.\" be provided or otherwise made available to, or used by, any
.\" other person.  No title to or ownership of the software is
.\" hereby transferred.
...
.V= $Header: fsirand.8 1.3 87/04/02 $
.\" @(#)fsirand.8 1.1 85/12/28 SMI;
.TH FSIRAND 8 "\*(V)" "4BSD"
.SH NAME
fsirand \- install random inode generation numbers
.SH SYNOPSIS
.B fsirand
[
.B \-p
] special
.SH DESCRIPTION
.\".IX  "fsirand command"  ""  "\f2fsirand\fP \(em install random inode generation numbers"
.I Fsirand
installs random inode generation numbers on all the inodes on device
.I special,
and also installs a filesystem ID in the superblock.
This helps increase the security of filesystems exported by NFS.
.LP
.I Fsirand
must be used only on an unmounted filesystem
that has been checked with
.IR fsck (8).
The only exception is that it can be used
on the root filesystem in single-user mode,
if the system is immediately re-booted afterwards.
.SH OPTIONS
.TP
.B \-p
Print out the generation numbers for all the inodes,
but do not change the generation numbers.
