.\" $Copyright:	$
.\" Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
.\" Sequent Computer Systems, Inc.   All rights reserved.
.\"  
.\" This software is furnished under a license and may be used
.\" only in accordance with the terms of that license and with the
.\" inclusion of the above copyright notice.   This software may not
.\" be provided or otherwise made available to, or used by, any
.\" other person.  No title to or ownership of the software is
.\" hereby transferred.
...
.V= $Header: update.8 1.5 86/05/13 $
.TH UPDATE 8 "\*(V)" "7th Edition"
.SH NAME
update \- periodically update the super block
.SH SYNOPSIS
.B /etc/update
.SH DESCRIPTION
.I Update
is a program that executes
the
.IR sync (2)
primitive every 30 seconds.
This insures that the file system
is fairly up to date in case of a crash.
This command should not be executed directly,
but should be executed out of the
initialization shell command file.
.SH "SEE ALSO"
sync(2), sync(8), init(8), rc(8)
