.\" $Copyright:	$
.\" Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
.\" Sequent Computer Systems, Inc.   All rights reserved.
.\"  
.\" This software is furnished under a license and may be used
.\" only in accordance with the terms of that license and with the
.\" inclusion of the above copyright notice.   This software may not
.\" be provided or otherwise made available to, or used by, any
.\" other person.  No title to or ownership of the software is
.\" hereby transferred.
...
.V= $Header: colrm.1 1.4 86/05/13 $
.TH COLRM 1 "\*(V)" "4BSD"
.SH NAME
colrm \- remove columns from a file
.SH SYNOPSIS
.B colrm
[
startcol
[
endcol
]
]
.SH DESCRIPTION
.I Colrm
removes selected columns from a file.  Input is taken from standard input.
Output is sent to standard output.
.PP
If called with one parameter the columns
of each line will be removed starting with the specified column.
If called with two parameters the columns from the first column
to the last column will be removed.
.PP
Column numbering starts with column 1.
.SH "SEE ALSO"
expand(1)
.SH AUTHOR
Jeff Schriebman
