.\" $Copyright:	$
.\" Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
.\" Sequent Computer Systems, Inc.   All rights reserved.
.\"  
.\" This software is furnished under a license and may be used
.\" only in accordance with the terms of that license and with the
.\" inclusion of the above copyright notice.   This software may not
.\" be provided or otherwise made available to, or used by, any
.\" other person.  No title to or ownership of the software is
.\" hereby transferred.
...
.V= $Header: fold.1 1.4 86/05/13 $
.TH FOLD 1 "\*(V)" "3BSD"
.SH NAME
fold \- fold long lines for finite width output device
.SH SYNOPSIS
.B fold
[
\-width
] [
file ...
]
.SH DESCRIPTION
.I Fold
is a filter which will fold the contents of the specified files,
or the standard input if no files are specified,
breaking the lines to have maximum width
.I width.
The default for
.I width
is 80.
.I Width
should be a multiple of 8 if tabs are present, or the tabs should
be expanded using
.IR expand (1)
before coming to
.I fold.
.SH SEE\ ALSO
expand(1)
.SH BUGS
If underlining is present it may be messed up by folding.
