.\" $Copyright:	$
.\" Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
.\" Sequent Computer Systems, Inc.   All rights reserved.
.\"  
.\" This software is furnished under a license and may be used
.\" only in accordance with the terms of that license and with the
.\" inclusion of the above copyright notice.   This software may not
.\" be provided or otherwise made available to, or used by, any
.\" other person.  No title to or ownership of the software is
.\" hereby transferred.
...
.V= $Header: lock.1 1.4 86/05/13 $
.TH LOCK 1 "\*(V)" "3BSD"
.SH NAME
lock \- reserve a terminal
.SH SYNOPSIS
.B lock
.SH DESCRIPTION
.I Lock
requests a password from the user, then prints "LOCKED" on
the terminal and refuses to relinquish the terminal until
the password is repeated.  If the user forgets the password,
he has no other recourse but to login elsewhere and kill
the lock process.
.SH AUTHOR
Kurt Shoens
.SH BUGS
Should timeout after 15 minutes.
