.\" $Copyright:	$
.\" Copyright (c) 1984, 1985, 1986 Sequent Computer Systems, Inc.
.\" All rights reserved
.\"  
.\" This software is furnished under a license and may be used
.\" only in accordance with the terms of that license and with the
.\" inclusion of the above copyright notice.   This software may not
.\" be provided or otherwise made available to, or used by, any
.\" other person.  No title to or ownership of the software is
.\" hereby transferred.
...
.V= $Header: pti.1 1.4 87/02/17 $
.TH PTI 1 "\*(V)" "4BSD"
.SH NAME
pti \- phototypesetter interpreter
.SH SYNOPSIS
.B pti
[ file ... ]
.SH DESCRIPTION
.I Pti
shows the commands in a stream from the standard output of
.IR troff (1)
using
.I troff's
.B \-t
option,
interpreting them as they would act on the typesetter.
Horizontal motions shows as counts in internal units and
are marked with `<' and `>' indicating left and right motion.
Vertical space is called
.I lead
and is also indicated.
.SH SEE ALSO
troff(1)
.SH BUGS
Too cryptic for normal users, who should use ``troff \-a ...''.
