.\" $Copyright:	$
.\" Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
.\" Sequent Computer Systems, Inc.   All rights reserved.
.\"  
.\" This software is furnished under a license and may be used
.\" only in accordance with the terms of that license and with the
.\" inclusion of the above copyright notice.   This software may not
.\" be provided or otherwise made available to, or used by, any
.\" other person.  No title to or ownership of the software is
.\" hereby transferred.
...
.V= $Header: size.1 1.5 86/05/13 $
.TH SIZE 1 "\*(V)" "7th Edition"
.SH NAME
size \- size of an object file
.SH SYNOPSIS
.B size
[ object ... ]
.SH DESCRIPTION
.I Size
prints the (decimal) number of bytes required by the text, data, and
bss portions, and their sum in hex and decimal, of each object-file argument.
If no file is specified,
.I a.out
is used.
If any of the argument files have shared data or bss, the sizes of
these are also printed.
.SH "SEE ALSO"
a.out(5)
