.\" $Copyright: $
.\" Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991
.\" Sequent Computer Systems, Inc.   All rights reserved.
.\"  
.\" This software is furnished under a license and may be used
.\" only in accordance with the terms of that license and with the
.\" inclusion of the above copyright notice.   This software may not
.\" be provided or otherwise made available to, or used by, any
.\" other person.  No title to or ownership of the software is
.\" hereby transferred.
...
.V= $Header: uptime.1 1.6 1991/06/13 00:02:39 $
.TH UPTIME 1 "\*(V)" "3BSD"
.SH NAME
uptime \- show how long system has been up
.SH SYNOPSIS
.B uptime
.SH DESCRIPTION
Uptime prints the current time, the length of time the system has been up,
and the number of jobs in the run queue,
divided by the number of processors in the system,
averaged over the last 1, 5 and
15 minutes.
It is, essentially, the first line of a
.IR w (1)
command.
.SH FILES
/dynix	system name list
.SH SEE ALSO
w(1)
