.\" $Copyright:	$
.\" Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
.\" Sequent Computer Systems, Inc.   All rights reserved.
.\"  
.\" This software is furnished under a license and may be used
.\" only in accordance with the terms of that license and with the
.\" inclusion of the above copyright notice.   This software may not
.\" be provided or otherwise made available to, or used by, any
.\" other person.  No title to or ownership of the software is
.\" hereby transferred.
...
.V= $Header: users.1 1.7 90/03/30 $
.TH USERS 1 "\*(V)" "4BSD"
.SH NAME
u, users \- compact list of users who are on the system
.SH SYNOPSIS
.B users
.br
   or
.br
.B u
.SH DESCRIPTION
.B Users
lists the login names of the users currently on the system, in a compact
one-line format.
.SH FILES
/etc/utmp
.SH SEE ALSO
who(1)
