.\" $Copyright:	$
.\" Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
.\" Sequent Computer Systems, Inc.   All rights reserved.
.\"  
.\" This software is furnished under a license and may be used
.\" only in accordance with the terms of that license and with the
.\" inclusion of the above copyright notice.   This software may not
.\" be provided or otherwise made available to, or used by, any
.\" other person.  No title to or ownership of the software is
.\" hereby transferred.
.\"
.\" This software is furnished under a license and may be used
.\" only in accordance with the terms of that license and with the
.\" inclusion of the above copyright notice.   This software may not
.\" be provided or otherwise made available to, or used by, any
.\" other person.  No title to or ownership of the software is
.\" hereby transferred.
...
.V= $Header: abort.3 1.7 86/08/15 $
.TH ABORT 3 "\*(V)" "7th Edition"
.SH NAME
abort \- generate a fault
.SH DESCRIPTION
.I Abort
executes an instruction which is illegal in user mode.
This causes a signal that normally terminates
the process with a core dump, which may be used for debugging.
.SH SEE ALSO
ddt(1), sigvec(2), exit(2)
.SH DIAGNOSTICS
Usually `Illegal instruction \- core dumped' from the shell.
.SH BUGS
The abort() function does not flush standard I/O buffers.  Use
\f2fflush\fP\|(3S).
