.\" $Copyright:	$
.\" Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
.\" Sequent Computer Systems, Inc.   All rights reserved.
.\"  
.\" This software is furnished under a license and may be used
.\" only in accordance with the terms of that license and with the
.\" inclusion of the above copyright notice.   This software may not
.\" be provided or otherwise made available to, or used by, any
.\" other person.  No title to or ownership of the software is
.\" hereby transferred.
...
.V= $Header: setuid.3 1.5 90/07/27 $
.TH SETUID 3 "\*(V)" "4BSD"
.SH NAME
setuid, seteuid, setruid, setgid, setegid, setrgid \- set user and group ID
.SH SYNOPSIS
.nf
.B setuid(uid)
.B seteuid(euid)
.B setruid(ruid)
.PP
.B setgid(gid)
.B setegid(egid)
.B setrgid(rgid)
.fi
.SH DESCRIPTION
.I Setuid
.RI ( setgid )
sets both the real and effective
user ID (group ID) of the current process to
as specified.
.PP
.I Seteuid
.RI ( setegid )
sets the effective user ID (group ID) of the
current process.
.PP
.I Setruid
.RI ( setrgid )
sets the real user ID (group ID) of the
current process.
.PP
These calls are only permitted to the super-user
or if the argument is the real or effective ID.
.SH "SEE ALSO"
setreuid(2), setregid(2), getuid(2), getgid(2)
.SH DIAGNOSTICS
Zero is returned if the user (group) ID is set;
\-1 is returned otherwise.
