#!/bin/sh

# $Copyright:	$
# Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
# Sequent Computer Systems, Inc.   All rights reserved.
#  
# This software is furnished under a license and may be used
# only in accordance with the terms of that license and with the
# inclusion of the above copyright notice.   This software may not
# be provided or otherwise made available to, or used by, any
# other person.  No title to or ownership of the software is
# hereby transferred.

# $Header: makerev 1.4 86/03/17 $

for sec in $*
do
	(
	cd ../man$sec
	for file in *.$sec*
	do
		sed -n '
			/^\.V=/{
				s|.*\(8[0-9]/[0-9][0-9]/[0-9][0-9]\) \$.*|\1|p
				q
			}' $file
	done
	)
done | sort -u -o revdates$1
ed - revdates$1 <<\EOF
2,$-c
 through 
.
1,$j
w
EOF
