# $Copyright:	$
# Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
# Sequent Computer Systems, Inc.   All rights reserved.
#  
# This software is furnished under a license and may be used
# only in accordance with the terms of that license and with the
# inclusion of the above copyright notice.   This software may not
# be provided or otherwise made available to, or used by, any
# other person.  No title to or ownership of the software is
# hereby transferred.

# $Header: Makefile.proto 1.5 86/01/29 $
#

STAGE=/techpubs/stage/man0
TPF = /usr/local/tpf
XROFF = $(TPF) -M -X
LASER = lpr -Plaser
TMACTITLE = tmac.ti

.SUFFIXES :
.SUFFIXES : .x .t .xr .nh .ti

# Use tpf for files that contain tpf macros.
.t.x :
	$(TPF) -X $< | tee $(STAGE)/$@ | $(LASER)
	rm -f $@
	ln -s $(STAGE)/$@

# Use straight xroff for files that contain no macros.
# Make 3 copies for the 3 parts.
.xr.x :
	$(XROFF) $< | tee $(STAGE)/$@ | $(LASER) -#3
	rm -f $@
	ln -s $(STAGE)/$@

# Use title page macros for title pages.
.ti.x :
	$(TPF) -X -M$(TMACTITLE) $< | tee $(STAGE)/$@ | $(LASER)
	rm -f $@
	ln -s $(STAGE)/$@

print:& titles \
	copyr.x \
	manuals.x \
	revisions \
	toc.x \
	ptx.x
	touch print

ptx.x: ptx1.x ptx2.x

ptx1.x: ptxmac1 ptxout1
	$(TPF) -X ptxmac1 ptxout1 | tee $(STAGE)/$@ | $(LASER)
	rm -f $@
	ln -s $(STAGE)/$@

ptx2.x: ptxmac2 ptxout2
	$(TPF) -X ptxmac2 ptxout2 | tee $(STAGE)/$@ | $(LASER)
	rm -f $@
	ln -s $(STAGE)/$@

# Divide ptxout up so that xroff can digest it.
ptxout1: ptxout
	head -1506 ptxout > ptxout1

ptxout2: ptxout
	sed '1,1506d' ptxout > ptxout2

ptxout: ptxin bfile ignore
	-ptx -r -f -t -w 110 -b bfile -i ignore < ptxin > ptxout

ptxin.proto: ptxin

ptxin: makeptx cshcmd
	makeptx > ptxin.proto
	cat ptxin.proto cshcmd > ptxin

# warning: if this changes, add/delete other "install" entries
# and update maketoc.
TOCLIST= toc1 toc2 toc3 toc3m toc3n toc3p toc3s toc3x toc3c toc4 toc5 toc6 toc7 toc8

# Make 3 copies of toc--one for each part.
toc.x: toc.in $(TOCLIST)
	$(TPF) -X -M../liberal toc.in | tee $(STAGE)/$@ | $(LASER) -#3
	rm -f $@
	ln -s $(STAGE)/$@

$(TOCLIST): maketoc ptxin.proto
	maketoc $@ > $@

revisions: revs1.x revs2.x revs4.x

revs1.x : revs1.t revdates1

revs2.x : revs2.t revdates2

revs4.x : revs4.t revdates4

revdates1:
	makerev 1
 
revdates2:
	makerev 2 3
 
revdates4:
	makerev 4 5 6 7 8

titles: title1.x title2.x title4.x

clean:
	rm -f *.x
	rm -f $(STAGE)/*.x
	rm -f ptxin ptxin.proto ptxout*
	rm -f $(TOCLIST)
	rm -f revdates?
	rm -f print
