# $Copyright:	$
# Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 
# Sequent Computer Systems, Inc.   All rights reserved.
#  
# This software is furnished under a license and may be used
# only in accordance with the terms of that license and with the
# inclusion of the above copyright notice.   This software may not
# be provided or otherwise made available to, or used by, any
# other person.  No title to or ownership of the software is
# hereby transferred.

# $Header: Makefile.proto 1.2 86/03/17 $
SRCS=	0.t 1.t 2.t 3.t 4.t 5.t 6.t 7.t
TROFF=	itroff

fs:	${SRCS}
	tbl ${SRCS} | ${TROFF} -ms -t > fs

paper:	fs
	lpr -Pimagen -t fs
